import { Customer } from "./customer";

export const CUSTOMERS: Customer[]= [
  {  cid: 1,
    password:"123",
    email: "xueyifan@mock.com",
    firstname: "Xueyi",
    lastname: "Fan",
    gender: "F",
    birthdate: "10-18-1989",
  },
  {  cid: 2,
    password:"234",
    email: "ruobinwu@mock.com",
    firstname: "Ruobin",
    lastname: "Wu",
    gender: "M",
    birthdate: "12-31-1989",
  },
  {  cid: 3,
    password:"345",
    email: "amy@mock.com",
    firstname: "Amy",
    lastname: "Fan",
    gender: "F",
    birthdate: "12-31-1989",
  },
  {  cid: 4,
    password:"456",
    email: "shirley@mock.com",
    firstname: "Shirley",
    lastname: "Fan",
    gender: "F",
    birthdate: "12-31-1989",
  },
]
