import { Course } from './course';

export const COURSES: Course[] = [
    {
        "cid": 1,
        "rid": 1,
        "category": "entree",
        "name": "halibut eggs benedict",
        "price": 15,
        "image": "https://s3-media3.fl.yelpcdn.com/bphoto/9A0iSEqXuKCEJgEHIuI2uw/o.jpg",
        "ingredient": "halibut, egg, english muffin",
        "option": "fully cooked, poached",
        "vegetarian": "N",
        "rating": 4,
        "waiting_time": 5,
        "new": "N"
    },
    {
        "cid": 2,
        "rid": 1,
        "category": "dessert",
        "name": "pulled pork johnny cakes",
        "price": 10,
        "image": "https://s3-media2.fl.yelpcdn.com/bphoto/4ar51TSoULeQX-ifN3BSMQ/o.jpg",
        "ingredient": "pork, pancake",
        "option": "",
        "vegetarian": "N",
        "rating": 4.5,
        "waiting_time": 10,
        "new": "N"
    },
    {
        "cid": 3,
        "rid": 1,
        "category": "salad",
        "name": "octopus salad",
        "price": 12,
        "image": "https://s3-media1.fl.yelpcdn.com/bphoto/FKBekwpNwXzfl_if42sz6g/o.jpg",
        "ingredient": "spinach, beet",
        "option": "",
        "vegetarian": "Y",
        "rating": 3,
        "waiting_time": 2,
        "new": "Y"
    },
    {
        "cid": 4,
        "rid": 1,
        "category": "entree",
        "name": "ceviche and chicharron",
        "price": 10,
        "image": "https://s3-media2.fl.yelpcdn.com/bphoto/qVEmU8PUqzjUE6N_CxauEw/o.jpg",
        "ingredient": "fish",
        "option": "",
        "vegetarian": "N",
        "rating": 4.2,
        "waiting_time": 3,
        "new": "N"
    },
    {
        "cid": 5,
        "rid": 1,
        "category": "entree",
        "name": "rib eye and frites",
        "price": 18,
        "image": "https://s3-media2.fl.yelpcdn.com/bphoto/47cXycxBA0x6e9-Ktb6Gww/o.jpg",
        "ingredient": "rib, potato",
        "option": "",
        "vegetarian": "N",
        "rating": 3.8,
        "waiting_time": 6,
        "new": "Y"
    },
    {
        "cid": 6,
        "rid": 1,
        "category": "entree",
        "name": "butcher's cut",
        "price": 25,
        "image": "https://s3-media3.fl.yelpcdn.com/bphoto/u5iscaG7USXEWXCzPqa3ng/o.jpg",
        "ingredient": "beef, potato",
        "option": "well, medium well, medium, rare, medium rare",
        "vegetarian": "N",
        "rating": 3.5,
        "waiting_time": 8,
        "new": "N"
    },
    {
        "cid": 7,
        "rid": 1,
        "category": "appetizer",
        "name": "beef al forno",
        "price": 20,
        "image": "https://s3-media3.fl.yelpcdn.com/bphoto/Yyw-7SMBus7BxnCMd2bjfA/o.jpg",
        "ingredient": "beef, cheese",
        "option": "",
        "vegetarian": "N",
        "rating": 3.9,
        "waiting_time": 8,
        "new": "N"
    },
    {
        "cid": 8,
        "rid": 1,
        "category": "dessert",
        "name": "ice cream smore",
        "price": 15,
        "image": "https://s3-media3.fl.yelpcdn.com/bphoto/bQxLPQLbzbR3e0iIIVMG-Q/o.jpg",
        "ingredient": "cream",
        "option": "",
        "vegetarian": "Y",
        "rating": 3.2,
        "waiting_time": 9,
        "new": "Y"
    },
    {
        "cid": 9,
        "rid": 1,
        "category": "salad",
        "name": "seasonal salad",
        "price": 8,
        "image": "https://s3-media3.fl.yelpcdn.com/bphoto/oUfu2pKNeSKE8Wwr7y1Uxg/o.jpg",
        "ingredient": "beet, tomato",
        "option": "",
        "vegetarian": "Y",
        "rating": 4.9,
        "waiting_time": 6,
        "new": "Y"
    },
    {
        "cid": 10,
        "rid": 3,
        "category": "entree",
        "name": "skirt steak",
        "price": 35,
        "image": "https://s3-media3.fl.yelpcdn.com/bphoto/qTKC3vkvsVjXHEIpNAEpHA/o.jpg",
        "ingredient": "beef, potato",
        "option": "",
        "vegetarian": "N",
        "rating": 4.8,
        "waiting_time": 5,
        "new": "N"
    },
    {
        "cid": 11,
        "rid": 3,
        "category": "entree",
        "name": "blackened stealhead trout",
        "price": 25,
        "image": "https://s3-media2.fl.yelpcdn.com/bphoto/EF9m9in-zp_WFZCDwMdTzw/o.jpg",
        "ingredient": "trout, corn, lettuce",
        "option": "",
        "vegetarian": "N",
        "rating": 4.5,
        "waiting_time": 7,
        "new": "Y"
    },
    {
        "cid": 12,
        "rid": 3,
        "category": "appetizer",
        "name": "bone marrow",
        "price": 22,
        "image": "https://s3-media1.fl.yelpcdn.com/bphoto/wAFPPlSuc8luAJyeYR996w/o.jpg",
        "ingredient": "marrow, bread, cheese",
        "option": "",
        "vegetarian": "N",
        "rating": 4,
        "waiting_time": 1,
        "new": "N"
    },
    {
        "cid": 13,
        "rid": 3,
        "category": "dessert",
        "name": "french toast",
        "price": 15,
        "image": "https://s3-media1.fl.yelpcdn.com/bphoto/kT3Ls3ltQHOiNlqKIIR2CA/o.jpg",
        "ingredient": "toast, strawberry, mint",
        "option": "",
        "vegetarian": "Y",
        "rating": 3,
        "waiting_time": 2,
        "new": "N"
    },
    {
        "cid": 14,
        "rid": 3,
        "category": "dessert",
        "name": "chacolate cake",
        "price": 10,
        "image": "https://s3-media1.fl.yelpcdn.com/bphoto/D5KpWZT5Ywwwd3EENpxf7A/o.jpg",
        "ingredient": "chacolate, cake",
        "option": "",
        "vegetarian": "Y",
        "rating": 2,
        "waiting_time": 3,
        "new": "Y"
    }
]